# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFufo4XTPFL0uslLu7egXzSzAU_egefP

# DAT 490 Capstone Project
## Group 6
## Alex Kazepides, Jacob Trainor, and Benjamin Wilcox
## October 19, 2025

Important Libraries
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import geopandas as gpd
from shapely.geometry import Point, Polygon
import numpy as np
import seaborn as sns
import plotly.express as px
import datetime

"""# U.S. Pollution Data 2000 - 2023
## Introduction

The main data set that we will be analyzing is the following data set, found on Kaggle:

https://www.kaggle.com/datasets/guslovesmath/us-pollution-data-200-to-2022

This data set is a collection of air pollution-based data that was originally taken from the U.S. Environmental Protection Agency. It has been condensed to provide key data on a select number of air pollutants, these being ozone (O3), carbon monoxide (CO), sulfur dioxide (SO2), and nitrogen dioxide (NO2) based on the air quality index (AQI). For each point of data, it also provides the date collected and the exact address, including the state, country, and city.

Here is a small snippet of the data for a clearer visualization.
"""

aqdf = pd.read_csv('pollution_2000_2023.csv')
aqdf.head()

"""Here is a representation of what some of the data will look like. The different measurements for the different air pollutants are also shown and are defined from the data set's source. The mean of a pollutant is it's mean density in the air throughout an entire day. The 1st max value is the maximum density the pollutant reached in the span of one day. The 1st max hour is the hour in which the pollutant reached its highest density for the day. The AQI shows the AQI score for that day in regards to that pollutant.

We will be analyzing these data in both Arizona and the U.S. as a whole in order to find key patterns and give sufficient context to our future research plans.

## Data Munging and Cleaning

To make the data easier to sort through, the date variable will be separated into three different variables, one each for the year, month, and day.
"""

aqdf['date_dt'] = pd.to_datetime(aqdf['Date'])
aqdf['day'] = aqdf['date_dt'].dt.day
aqdf['month'] = aqdf['date_dt'].dt.month
aqdf['year'] = aqdf['date_dt'].dt.year
aqdf.head()

"""We will also need to clean our data, but keep a version of the data pre-cleaning in order to explore both facets."""

print("Pre-Cleaning Size:",aqdf.shape)
aqdfClean = aqdf.dropna()
print("Post-Cleaning Size:",aqdfClean.shape)

"""As it turns out, even after visually scanning our data, there are no data points with any unknown values in this data set, making our analysis easier as we only need to analyze this one data set with no cleaning involved. One interesting note, however, is that some values in the City variable are listed as "Not in a city," which we may want to disaggregate later. Here is an example of a full row with this characteristic."""

print(aqdf.loc[[613369]])

"""## Arizona Analysis

The target variables in this data set will be each of the variables that have to do with an air pollutant, such as SO2 Mean and CO AQI. The rest of the variables will be the features that we will use to analyze our target variables. These will be columns that describe the location or date of collection.

### Average AQI by Year

First, we will take a look at characteristics of the data in Arizona alone. Then, we will move on to analyzing the data in the U.S. as a whole. The AQI is a significant indicator of air pollution, as it determines its levels of danger, so we will start there. It should be noted from previous research, that the danger level indicated by AQI increases for every 50 points. Here is a plot that depicts the average AQI of each of the pollutants by year.
"""

aqdfAZ = aqdf[aqdf['State'] == 'Arizona']

means = aqdfAZ.groupby('year')[['O3 AQI', 'CO AQI', 'SO2 AQI', 'NO2 AQI']].mean()
means.plot(figsize=(10,6), grid=True,
           xlabel='Year', ylabel='Average AQI',
           title='Average AQI by Year in Arizona')
plt.legend(title='Pollutant')
plt.show()

"""This plot shows that three out of the four pollutants are decreasing in AQI score as time passes. Ozone is the only pollutant that trended upwards. Although NO2 and O3 started at near the same average AQI, only NO2 tends to decrease over time. The other two pollutants, CO and SO2, started at lower average AQI values and ended at even lower values. However, it seems that these two pollutants also saw smaller overall changes than either O3 or NO2.

These results show that CO, SO2, and NO2 are decreasing over time, which is a positive change. However, the increase in Ozone's AQI, especially being over 50, is a negative indicator of this facet of air quality.

### Mean vs AQI for Pollutants

Now that we have an idea of how the AQI for each pollutant changes, let's discover what variables are influencing this. We will take the mean column for each pollutant and compare this to the AQI for each day.
"""

plt.figure(figsize=(10, 6))
sns.regplot(
    data=aqdfAZ,
    x='O3 Mean',
    y='O3 AQI',
    scatter_kws={
        'color': 'blue',        # dot color
        'alpha': 0.45,
        's': 40,
        'edgecolor': 'k'
    },
    line_kws={
        'color': 'red',
        'zorder': 3
    },
    ci=95
)
plt.xlabel('O3 Mean')
plt.ylabel('O3 AQI')
plt.title('O3 Mean vs O3 AQI in Arizona')
plt.grid(alpha=0.25)
plt.show()

"""For O3's measurements, we see a clear positive relationship with the mean and AQI daily. It also seems that more variance occurs when the mean is higher, leading to more differing AQI values at these higher means. Although there are some outliers, the relationship here is clearly positive and demonstrates how the average increase in O3 density daily causes in increase in AQI.

Now, let's look at CO.
"""

plt.figure(figsize=(10, 6))
sns.regplot(
    data=aqdfAZ,
    x='CO Mean',
    y='CO AQI',
    scatter_kws={
        'color': 'yellow',        # dot color
        'alpha': 0.45,
        's': 40,
        'edgecolor': 'k'
    },
    line_kws={
        'color': 'red',
        'zorder': 3
    },
    ci=95
)
plt.xlabel('CO Mean')
plt.ylabel('CO AQI')
plt.title('CO Mean vs CO AQI in Arizona')
plt.grid(alpha=0.25)
plt.show()

"""asdf"""

plt.figure(figsize=(10, 6))
sns.regplot(
    data=aqdfAZ,
    x='SO2 Mean',
    y='SO2 AQI',
    scatter_kws={
        'color': 'red',        # dot color
        'alpha': 0.45,
        's': 40,
        'edgecolor': 'k'
    },
    line_kws={
        'color': 'blue',
        'zorder': 3
    },
    ci=95
)
plt.xlabel('SO2 Mean')
plt.ylabel('SO2 AQI')
plt.title('SO2 Mean vs SO2 AQI in Arizona')
plt.grid(alpha=0.25)
plt.show()

"""SO2 is a similar case to O3, showing a positive correlation between mean and AQI. We can begin to see here, however, that the mean density of SO2 averages around significantly higher values than those in O3. This is due to the difference in weights and densities between these compounds, and would be insignificant to compare. We do see again that there can be a decent amount of variance in AQI based on the mean, similar to O3.

Next is NO2.
"""

air_qualitydf = pd.read_csv('pollution_2000_2023.csv')
air_qualitydf.head()
aq_az = air_qualitydf[air_qualitydf['State'] == 'Arizona']
aq_az.head()

plt.hist(air_qualitydf['O3 Mean'], bins = 30, color = 'skyblue', edgecolor = 'black')
plt.xlabel('O3 Mean Concentration')
plt.ylabel('Frequency')
plt.title('Distribution of O3 Concentration in Arizona')

plt.hist(air_qualitydf['CO Mean'], bins = 30, color = 'magenta', edgecolor = 'black')
plt.xlabel('CO Concentration')
plt.ylabel('Frequency')
plt.title('Distribution of CO Concentration in Arizona')

plt.hist(air_qualitydf['SO2 Mean'], bins = 30, color = 'yellow', edgecolor = 'black')
plt.xlabel('SO2 Concentration')
plt.ylabel('Frequency')
plt.title('Distribution of SO2 Concentration in Arizona')

plt.hist(air_qualitydf['NO2 Mean'], bins = 30, color = 'green', edgecolor = 'black')
plt.xlabel('NO2 Concentration')
plt.ylabel('Frequency')
plt.title('Distribution of NO2 Concentration in Arizona')

corr_matrix = poldf[['O3 Mean', 'CO Mean', 'SO2 Mean', 'NO2 Mean']].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='vlag', center=0)
plt.title('Air Pollutant Correlation Matrix')
plt.show()

"""# Climate Global Time Series
## Introduction
The data will be showcased through geospatial data and multiple linear regressions with multiple datasets. https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/2/tavg/1/7/1895-2025 This website contained
"""

az_climate2018 = pd.read_csv('AZClimateData2018.csv')
az_climate2018 = az_climate2018.iloc[3:,]
az_climate2018 = az_climate2018.rename(columns={'# Title: July 2018 Arizona County Maximum Temperature':'ID',
                                                'Unnamed: 1':'County',
                                                'Unnamed: 2':'State',
                                                'Unnamed: 3':'Max Temperature',
                                                'Unnamed: 4':'Rank',
                                                'Unnamed: 5':'Anomaly',
                                                'Unnamed: 6':'Mean'})
az_climate2018['Max Temperature'] = pd.to_numeric(az_climate2018['Max Temperature'], errors='coerce')
az_climate2018.head()

plt.figure(figsize=(30, 10))
plt.bar(az_climate2018['County'], az_climate2018['Max Temperature'])
plt.xlabel('County')
plt.ylabel('Max Temperature')
plt.title('Max Temperature by County in Arizona')
plt.show()

az_avg_temp = pd.read_csv('AZ_AVGTemp.csv')
az_avg_temp = az_avg_temp.iloc[2:]
az_avg_temp = az_avg_temp.rename(columns={'#  Arizona July Average Temperature':'year',
    'Unnamed: 1': 'Average Temperature'})
az_avg_temp['year'] = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023]
az_avg_temp.head()
az_avg_temp['Average Temperature'].dtype
az_avg_temp['Average Temperature'] = pd.to_numeric(az_avg_temp['Average Temperature'], errors='coerce')

plt.figure(figsize=(10, 6))
plt.plot(az_avg_temp['year'], az_avg_temp['Average Temperature'])
plt.xlabel('Year')
plt.ylabel('Average Temperature (°F)')
plt.title('Arizona July Average Temperature (2000-2023)')
plt.grid(True)
plt.show()

temp_merge2018 = pd.merge(aqdfAZ, az_climate2018, on='County', how='left')
temp_merge2018 = temp_merge2018[['County', 'NO2 Mean', 'year', 'month']]
temp_merge2018 = temp_merge2018[temp_merge2018['year']==2018]
temp_merge2018 = temp_merge2018[temp_merge2018['month']==7]
temp_merge2018.head()

avg_merge = pd.merge(aqdf, az_avg_temp, on='year', how='left')
avg_merge.head()

counties = gpd.read_file('https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_county_500k.zip')
az_counties = counties[counties['STATEFP'] == '04']
az_counties =az_counties.rename(columns={'NAME':'County'})
az_counties.head()

az_counties = az_counties.to_crs(epsg=5070)

az_counties.plot(edgecolor='black', facecolor='lightblue', figsize=(8,8))

aq_summary = avg_merge.groupby('County').agg({
    'O3 Mean': 'mean',
    'CO Mean': 'mean',
    'SO2 Mean': 'mean',
    'NO2 Mean': 'mean'})
aq_summary.head()

aq_map_merge = pd.merge(az_counties, aq_summary, on='County', how='left')
aq_map_merge.head()

fig, axs = plt.subplots(2, 2, figsize=(15, 15))

aq_map_merge.plot(column="NO2 Mean", ax=axs[0,0], legend=True, cmap="viridis")
axs[0,0].set_title("NO2 Mean by County in Arizona")

aq_map_merge.plot(column="CO Mean", ax=axs[0,1], legend=True, cmap="plasma")
axs[0,1].set_title("CO Mean by County in Arizona")

aq_map_merge.plot(column="SO2 Mean", ax=axs[1,0], legend=True, cmap="inferno")
axs[1,0].set_title("SO2 Mean by County in Arizona")

aq_map_merge.plot(column="O3 Mean", ax=axs[1,1], legend=True, cmap="magma")
axs[1,1].set_title("O3 Mean by County in Arizona")

plt.tight_layout()
plt.show()

merge_df = pd.merge(aq_map_merge, avg_merge, on='County', how='left')
merge_df = merge_df.dropna()
merge_df = merge_df.drop_duplicates()
merge_df = merge_df[['year', 'Average Temperature', 'NO2 AQI', 'SO2 AQI', 'O3 AQI', 'CO AQI']]
merge_df['year'] = pd.to_numeric(merge_df['year'], errors='coerce')
merge_df['NO2 AQI'] = pd.to_numeric(merge_df['NO2 AQI'], errors='coerce')
merge_df['SO2 AQI'] = pd.to_numeric(merge_df['SO2 AQI'], errors='coerce')
merge_df['O3 AQI'] = pd.to_numeric(merge_df['O3 AQI'], errors='coerce')
no2 = merge_df.groupby('year')['NO2 AQI'].mean()
temp = merge_df.groupby('year')['Average Temperature'].mean()
so2 = merge_df.groupby('year')['SO2 AQI'].mean()
o3 = merge_df.groupby('year')['O3 AQI'].mean()
co = merge_df.groupby('year')['CO AQI'].mean()
merge_df.head()

fig, axs = plt.subplots(2, 2, figsize=(15, 15))

axs[0,0].scatter(no2, temp, marker='o', color='b')
axs[0,0].set_xlabel('NO2 AQI')
axs[0,0].set_ylabel('Average Temperature')
axs[0,0].set_title('NO2 AQI vs. Average Temperature')

axs[0,1].scatter(so2, temp, marker='o', color='r')
axs[0,1].set_xlabel('SO2 AQI')
axs[0,1].set_ylabel('Average Temperature')
axs[0,1].set_title('SO2 AQI vs. Average Temperature')

axs[1,0].scatter(o3, temp, marker='o', color='g')
axs[1,0].set_xlabel('O3 AQI')
axs[1,0].set_ylabel('Average Temperature')
axs[1,0].set_title('O3 AQI vs. Average Temperature')

axs[1,1].scatter(co, temp, marker='o', color='y')
axs[1,1].set_xlabel('CO AQI')
axs[1,1].set_ylabel('Average Temperature')
axs[1,1].set_title('CO AQI vs. Average Temperature')

plt.tight_layout()
plt.show()

temp_corr = merge_df['Average Temperature'].corr(merge_df['NO2 AQI'])
print("Correlation between Average Temperature and NO2 mean:", temp_corr)



"""# USDA Economic Research Service - Unemployment and Household Income
## Introduction


"""

undf = pd.read_csv('Unemployment2023.csv')

unemployment_df = undf[
    undf['Attribute'].str.contains('Unemployment_rate') &
    (undf['FIPS_Code'] > 1000)
].copy()

unemployment_df['Year'] = unemployment_df['Attribute'].str.split('_').str[-1].astype(int)
unemployment_df['County'] = unemployment_df['Area_Name'].apply(lambda x: x.split(',')[0].replace(' County', ''))
unemployment_df.rename(columns={'Value': 'Unemployment Rate', 'State': 'State_Abbr'}, inplace=True)
unemployment_df = unemployment_df[['Year', 'State_Abbr', 'County', 'Unemployment Rate']]

poldf = pd.read_csv('pollution_2000_2023.csv')
poldf['Date'] = pd.to_datetime(poldf['Date'])
poldf['Year'] = poldf['Date'].dt.year

state_mapping = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
    'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
    'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA',
    'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH',
    'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC',
    'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA',
    'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD', 'Tennessee': 'TN',
    'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
    'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY', 'District Of Columbia': 'DC',
    'Puerto Rico': 'PR'
}
poldf['State_Abbr'] = poldf['State'].map(state_mapping)
pollution_df = poldf.groupby(['Year', 'State_Abbr', 'County'])['NO2 Mean'].mean().reset_index()
merged_df = pd.merge(unemployment_df, pollution_df, on=['Year', 'State_Abbr', 'County'])
merged_df.dropna(inplace=True)

"""The unemployed dataset contains several metrics to categorize unemployment. That includes total population that is unemployed, percentage, and 20 others. So I created a copy of the undf import that selects for the proper category (attribute). Then the datset has its columns renamed to be more accurate to the selected attribute aand then we also remove the work county from each counties name to match the other dataset. A second import of the pollution csv is created to modify to match the unemployment one, and the states are changed from abbreviations to their full names."""

overall_correlation = merged_df['Unemployment Rate'].corr(merged_df['NO2 Mean'])
print(f"Overall Correlation (2000-2023): {overall_correlation:.4f}")

plt.figure(figsize=(12, 7))
sns.regplot(data=merged_df, x='NO2 Mean', y='Unemployment Rate', line_kws={"color": "red"}, scatter_kws={'alpha': 0.1})
plt.title('Unemployment Rate vs. NO2 Mean by County (2000-2023)')
plt.xlabel('Average Annual NO2 Mean')
plt.ylabel('Unemployment Rate (%)')
plt.grid(True)
plt.show()

"""This graph shows the relationship for all recorded counties by their average annual NO2 pollution and their unemployment rate. The results is a correlation of 0.1698. So it is not a very high relationship but it certainly shows evidence that pollution is related to unemployment. Which would indicate other poor economic metrics."""

correlation_by_year = merged_df.groupby('Year')[['Unemployment Rate', 'NO2 Mean']].corr().unstack().iloc[:, 1]

plt.figure(figsize=(12, 6))
correlation_by_year.plot(marker='o')
plt.title('Correlation between Unemployment and NO2 Mean Over Time')
plt.xlabel('Year')
plt.ylabel('Correlation')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
plt.show()

"""This graph shows the yearly coorelation between pollution and unemployment and this makes it more clear that the relationship is likely true. It also, shows that before the 2008 and 2020 recessions there is a drop in correlation. Those economic events could be the explaination for those."""

poldf_az = poldf[poldf['State_Abbr'] == 'AZ'].copy()
pollution_df = poldf_az.groupby(['Year', 'State_Abbr', 'County'])['NO2 Mean'].mean().reset_index()

merged_df = pd.merge(unemployment_df, pollution_df, on=['Year', 'State_Abbr', 'County'])
merged_df.dropna(inplace=True)

overall_correlation = merged_df['Unemployment Rate'].corr(merged_df['NO2 Mean'])
print(f"Overall Correlation for Arizona (2000-2023): {overall_correlation:.4f}")

plt.figure(figsize=(12, 7))
sns.regplot(data=merged_df, x='NO2 Mean', y='Unemployment Rate', line_kws={"color": "red"}, scatter_kws={'alpha': 0.3})
plt.title('Unemployment Rate vs. NO2 Mean in Arizona Counties (2000-2023)')
plt.xlabel('Average Annual NO2 Mean')
plt.ylabel('Unemployment Rate (%)')
plt.grid(True)
plt.show()

"""This graph only looks at Arizona counties between 2000 and 2023. The result is a negative correlation of -0.1. Though Arizona is likely an outlier when it comes to the national relationship. This is because Arizona's population is focused in two metro areas (Pheonix and Tuscon) and both are represented by one county. Those two counties will then have higher pollution averages as that is where most people live and their unemployment is likely to be lower than more rural counties."""

state_unemployment_df = unemployment_df.groupby(['Year', 'State_Abbr'])['Unemployment Rate'].mean().reset_index()

state_pollution_df = poldf.groupby(['Year', 'State_Abbr'])['NO2 Mean'].mean().reset_index()

merged_df = pd.merge(state_unemployment_df, state_pollution_df, on=['Year', 'State_Abbr'])
merged_df.dropna(inplace=True)

overall_correlation = merged_df['Unemployment Rate'].corr(merged_df['NO2 Mean'])
print(f"Overall State-Level Correlation (2000-2023): {overall_correlation:.4f}")

plt.figure(figsize=(12, 7))
sns.regplot(data=merged_df, x='NO2 Mean', y='Unemployment Rate', line_kws={"color": "red"}, scatter_kws={'alpha': 0.3})
plt.title('State-Level Unemployment Rate vs. NO2 Mean (2000-2023)')
plt.xlabel('Average Annual NO2 Mean (State)')
plt.ylabel('Average Annual Unemployment Rate (State %)')
plt.grid(True)
plt.savefig('state_unemployment_vs_pollution.png')
plt.show()

correlation_by_year = merged_df.groupby('Year')[['Unemployment Rate', 'NO2 Mean']].corr().unstack().iloc[:, 1]


plt.figure(figsize=(12, 6))
correlation_by_year.plot(marker='o')
plt.title('State-Level Correlation between Unemployment and NO2 Mean Over Time')
plt.xlabel('Year')
plt.ylabel('Pearson Correlation')
plt.grid(True)
plt.axhline(0, color='black', linewidth=0.8, linestyle='--')
plt.savefig('state_correlation_over_time.png')
plt.show()

"""# Results, Implications, Challenges

## Research Question
"""

from scipy import stats

# Filter data for early and late years
o3_early_years = aqdf[aqdf['year'].isin([2000, 2001, 2002])]['O3 Mean']
o3_late_years = aqdf[aqdf['year'].isin([2021, 2022, 2023])]['O3 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(o3_early_years, o3_late_years, nan_policy='omit')

print(f"T-test results for O3 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in O3 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in O3 Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
co_early_years = aqdf[aqdf['year'].isin([2000, 2001, 2002])]['CO Mean']
co_late_years = aqdf[aqdf['year'].isin([2021, 2022, 2023])]['CO Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(co_early_years, co_late_years, nan_policy='omit')

print(f"T-test results for CO Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in CO Mean between the early and late years is statistically significant.")
else:
    print("  The difference in CO Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
so2_early_years = aqdf[aqdf['year'].isin([2000, 2001, 2002])]['SO2 Mean']
so2_late_years = aqdf[aqdf['year'].isin([2021, 2022, 2023])]['SO2 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(so2_early_years, so2_late_years, nan_policy='omit')

print(f"T-test results for SO2 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in SO2 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in SO2 Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
no2_early_years = aqdf[aqdf['year'].isin([2000, 2001, 2002])]['NO2 Mean']
no2_late_years = aqdf[aqdf['year'].isin([2021, 2022, 2023])]['NO2 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(no2_early_years, no2_late_years, nan_policy='omit')

print(f"T-test results for NO2 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in NO2 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in NO2 Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
o3_early_years = aqdfAZ[aqdfAZ['year'].isin([2000, 2001, 2002])]['O3 Mean']
o3_late_years = aqdfAZ[aqdfAZ['year'].isin([2021, 2022, 2023])]['O3 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(o3_early_years, o3_late_years, nan_policy='omit')

print(f"T-test results for O3 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in O3 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in O3 Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
co_early_years = aqdfAZ[aqdfAZ['year'].isin([2000, 2001, 2002])]['CO Mean']
co_late_years = aqdfAZ[aqdfAZ['year'].isin([2021, 2022, 2023])]['CO Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(co_early_years, co_late_years, nan_policy='omit')

print(f"T-test results for CO Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in CO Mean between the early and late years is statistically significant.")
else:
    print("  The difference in CO Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
so2_early_years = aqdfAZ[aqdfAZ['year'].isin([2000, 2001, 2002])]['SO2 Mean']
so2_late_years = aqdfAZ[aqdfAZ['year'].isin([2021, 2022, 2023])]['SO2 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(so2_early_years, so2_late_years, nan_policy='omit')

print(f"T-test results for SO2 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in SO2 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in SO2 Mean between the early and late years is not statistically significant.")

# Filter data for early and late years
no2_early_years = aqdfAZ[aqdfAZ['year'].isin([2000, 2001, 2002])]['NO2 Mean']
no2_late_years = aqdfAZ[aqdfAZ['year'].isin([2021, 2022, 2023])]['NO2 Mean']

# Perform independent samples t-test
ttest_result = stats.ttest_ind(no2_early_years, no2_late_years, nan_policy='omit')

print(f"T-test results for NO2 Mean (2000-2002 vs 2021-2023):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in NO2 Mean between the early and late years is statistically significant.")
else:
    print("  The difference in NO2 Mean between the early and late years is not statistically significant.")

# Filter data for Arizona
aqdf_az = aqdf[aqdf['State'] == 'Arizona']

# Calculate the mean O3 Mean for Arizona (2000-2023)
o3_mean_az = aqdf_az['O3 Mean'].mean()

# Calculate the overall mean O3 Mean for the entire dataset (2000-2023)
o3_mean_overall = aqdf['O3 Mean'].mean()

print(f"Average O3 Mean in Arizona (2000-2023): {o3_mean_az:.4f}")
print(f"Overall Average O3 Mean (2000-2023): {o3_mean_overall:.4f}")

from scipy import stats

# Get the O3 Mean data for Arizona and the entire dataset
o3_az = aqdf[aqdf['State'] == 'Arizona']['O3 Mean']
o3_overall = aqdf['O3 Mean']

# Perform independent samples t-test
# We assume unequal variances since the sample sizes and potential distributions might differ.
ttest_result_az_overall = stats.ttest_ind(o3_az, o3_overall, equal_var=False, nan_policy='omit')

print(f"T-test results for O3 Mean (Arizona vs Overall):")
print(f"  T-statistic: {ttest_result_az_overall.statistic:.4f}")
print(f"  P-value: {ttest_result_az_overall.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result_az_overall.pvalue < alpha:
    print("  The difference in O3 Mean between Arizona and the overall dataset is statistically significant.")
else:
    print("  The difference in O3 Mean between Arizona and the overall dataset is not statistically significant.")

import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdf, x='year', y='O3 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('O3 Mean vs. Year, U.S.')
plt.xlabel('Year')
plt.ylabel('O3 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdf['year'], aqdf['O3 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdf, x='year', y='CO Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('CO Mean vs. Year, U.S.')
plt.xlabel('Year')
plt.ylabel('CO Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdf['year'], aqdf['CO Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdf, x='year', y='SO2 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('SO2 Mean vs. Year, U.S.')
plt.xlabel('Year')
plt.ylabel('SO2 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdf['year'], aqdf['SO2 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdf, x='year', y='NO2 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('NO2 Mean vs. Year, U.S.')
plt.xlabel('Year')
plt.ylabel('NO2 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdf['year'], aqdf['NO2 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdfAZ, x='year', y='O3 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('O3 Mean vs. Year, Arizona')
plt.xlabel('Year')
plt.ylabel('O3 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdfAZ['year'], aqdfAZ['O3 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdfAZ, x='year', y='CO Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('CO Mean vs. Year, Arizona')
plt.xlabel('Year')
plt.ylabel('CO Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdfAZ['year'], aqdfAZ['CO Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdfAZ, x='year', y='SO2 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('SO2 Mean vs. Year, Arizona')
plt.xlabel('Year')
plt.ylabel('SO2 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdfAZ['year'], aqdfAZ['SO2 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

# Create a regression plot
plt.figure(figsize=(10, 6))
sns.regplot(data=aqdfAZ, x='year', y='NO2 Mean',
            scatter_kws={'alpha': 0.3, 's': 10}, # Adjust alpha and size for points
            line_kws={'color': 'red', 'linewidth': 2}) # Set line color and width
plt.title('NO2 Mean vs. Year, Arizona')
plt.xlabel('Year')
plt.ylabel('NO2 Mean')
plt.grid(True)
plt.show()

# Calculate the slope of the regression line
slope, intercept, r_value, p_value, std_err = stats.linregress(aqdfAZ['year'], aqdfAZ['NO2 Mean'])

print(f"Slope of the regression line: {slope:.6f}")
print(f"P-value: {p_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")

means = aqdfAZ.groupby('year')[['O3 AQI', 'CO AQI', 'SO2 AQI', 'NO2 AQI']].mean()
means.plot(figsize=(10,6), grid=True,
           xlabel='Year', ylabel='Average AQI',
           title='Average AQI by Year in Arizona')
plt.legend(title='Pollutant')
plt.show()

means = aqdf.groupby('year')[['O3 AQI', 'CO AQI', 'SO2 AQI', 'NO2 AQI']].mean()
means.plot(figsize=(10,6), grid=True,
           xlabel='Year', ylabel='Average AQI',
           title='Average AQI by Year in the U.S.')
plt.legend(title='Pollutant')
plt.show()

from scipy import stats
import pandas as pd
# Define the split date
split_date = pd.to_datetime('2004-01-24')

# Split the data into two periods
before_split_df = aqdf[aqdf['Date'] < split_date].copy()
after_split_df = aqdf[aqdf['Date'] >= split_date].copy()

# Perform linear regression for the period before the split date
if not before_split_df.empty:
    slope_before, intercept_before, r_value_before, p_value_before, std_err_before = stats.linregress(before_split_df['year'], before_split_df['CO Mean'])
    print(f"Linear regression results for CO Mean before {split_date.date()}:")
    print(f"  Slope: {slope_before:.6f}")
    print(f"  P-value: {p_value_before:.4f}")
    print(f"  R-squared: {r_value_before**2:.4f}")
else:
    print(f"No data available before {split_date.date()} to perform regression.")
    slope_before = None

print("\n" + "="*50 + "\n")

# Perform linear regression for the period after the split date
if not after_split_df.empty:
    slope_after, intercept_after, r_value_after, p_value_after, std_err_after = stats.linregress(after_split_df['year'], after_split_df['CO Mean'])
    print(f"Linear regression results for CO Mean after {split_date.date()}:")
    print(f"  Slope: {slope_after:.6f}")
    print(f"  P-value: {p_value_after:.4f}")
    print(f"  R-squared: {r_value_after**2:.4f}")
else:
    print(f"No data available after {split_date.date()} to perform regression.")
    slope_after = None

# Compare the slopes
if slope_before is not None and slope_after is not None:
    slope_change = slope_after - slope_before
    print(f"\nChange in slope of CO Mean rate of change: {slope_change:.6f}")

from scipy import stats

# Assuming 'before_split_df' and 'after_split_df' are already created as in the previous cell

# Perform independent samples t-test on CO Mean
ttest_result = stats.ttest_ind(before_split_df['CO Mean'], after_split_df['CO Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for CO Mean (before vs after {split_date.date()}):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in CO Mean between the two periods is statistically significant.")
else:
    print("  The difference in CO Mean between the two periods is not statistically significant.")

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Assuming 'aqdf' is already loaded and 'Date' column is in datetime format
# Define the split date
split_date = pd.to_datetime('2004-01-24')

# Create a new column to indicate the period
aqdf['Period'] = aqdf['Date'].apply(lambda x: f'Before {split_date.date()}' if x < split_date else f'After {split_date.date()}')

# Create a box plot
plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdf, x='Period', y='CO Mean', showfliers=False)
plt.title('Distribution of CO Mean Before and After 2004-01-24')
plt.xlabel('Period')
plt.ylabel('CO Mean')
plt.grid(True)
plt.show()

split_date = pd.to_datetime('2004-01-24')

# Create a new column to indicate the period
aqdf['Period'] = aqdf['Date'].apply(lambda x: f'Before {split_date.date()}' if x < split_date else f'After {split_date.date()}')

# Create a box plot
plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdf, x='Period', y='O3 Mean', showfliers=False)
plt.title('Distribution of O3 Mean Before and After 2004-01-24')
plt.xlabel('Period')
plt.ylabel('O3 Mean')
plt.grid(True)
plt.show()

split_date = pd.to_datetime('2004-01-24')

# Create a new column to indicate the period
aqdf['Period'] = aqdf['Date'].apply(lambda x: f'Before {split_date.date()}' if x < split_date else f'After {split_date.date()}')

# Create a box plot
plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdf, x='Period', y='SO2 Mean', showfliers=False)
plt.title('Distribution of SO2 Mean Before and After 2004-01-24')
plt.xlabel('Period')
plt.ylabel('SO2 Mean')
plt.grid(True)
plt.show()

split_date = pd.to_datetime('2004-01-24')

# Create a new column to indicate the period
aqdf['Period'] = aqdf['Date'].apply(lambda x: f'Before {split_date.date()}' if x < split_date else f'After {split_date.date()}')

# Create a box plot
plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdf, x='Period', y='NO2 Mean', showfliers=False)
plt.title('Distribution of NO2 Mean Before and After 2004-01-24')
plt.xlabel('Period')
plt.ylabel('NO2 Mean')
plt.grid(True)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Assuming 'aqdfAZ' is already loaded and 'Date' column is in datetime format
# Define the split date
split_date = pd.to_datetime('2004-01-24')

# Ensure the 'Date' column in aqdfAZ is in datetime format
aqdfAZ['Date'] = pd.to_datetime(aqdfAZ['Date'])

# Create a new column to indicate the period for Arizona data
aqdfAZ['Period'] = aqdfAZ['Date'].apply(lambda x: f'Before {split_date.date()}' if x < split_date else f'After {split_date.date()}')

# Create a box plot for CO Mean in Arizona
plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdfAZ, x='Period', y='CO Mean', showfliers=False) # showfliers=False to hide outliers for better visualization of the main distribution
plt.title('Distribution of CO Mean Before and After 2004-01-24 in Arizona')
plt.xlabel('Period')
plt.ylabel('CO Mean')
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdfAZ, x='Period', y='O3 Mean', showfliers=False) # showfliers=False to hide outliers for better visualization of the main distribution
plt.title('Distribution of O3 Mean Before and After 2004-01-24 in Arizona')
plt.xlabel('Period')
plt.ylabel('O3 Mean')
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdfAZ, x='Period', y='SO2 Mean', showfliers=False) # showfliers=False to hide outliers for better visualization of the main distribution
plt.title('Distribution of SO2 Mean Before and After 2004-01-24 in Arizona')
plt.xlabel('Period')
plt.ylabel('SO2 Mean')
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=aqdfAZ, x='Period', y='NO2 Mean', showfliers=False) # showfliers=False to hide outliers for better visualization of the main distribution
plt.title('Distribution of NO2 Mean Before and After 2004-01-24 in Arizona')
plt.xlabel('Period')
plt.ylabel('NO2 Mean')
plt.grid(True)
plt.show()

ttest_result = stats.ttest_ind(before_split_df['CO Mean'], after_split_df['CO Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for CO Mean (before vs after {split_date.date()}):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in CO Mean between the two periods is statistically significant.")
else:
    print("  The difference in CO Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_df['O3 Mean'], after_split_df['O3 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for O3 Mean (before vs after {split_date.date()}):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in O3 Mean between the two periods is statistically significant.")
else:
    print("  The difference in O3 Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_df['SO2 Mean'], after_split_df['SO2 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for SO2 Mean (before vs after {split_date.date()}):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in SO2 Mean between the two periods is statistically significant.")
else:
    print("  The difference in SO2 Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_df['NO2 Mean'], after_split_df['NO2 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for NO2 Mean (before vs after {split_date.date()}):")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in NO2 Mean between the two periods is statistically significant.")
else:
    print("  The difference in NO2 Mean between the two periods is not statistically significant.")

before_split_dfAZ = aqdfAZ[aqdfAZ['Date'] < split_date].copy()
after_split_dfAZ = aqdfAZ[aqdfAZ['Date'] >= split_date].copy()

ttest_result = stats.ttest_ind(before_split_dfAZ['CO Mean'], after_split_dfAZ['CO Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for CO Mean (before vs after {split_date.date()}) in Arizona:")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in CO Mean between the two periods is statistically significant.")
else:
    print("  The difference in CO Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_dfAZ['O3 Mean'], after_split_dfAZ['O3 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for O3 Mean (before vs after {split_date.date()}) in Arizona:")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in O3 Mean between the two periods is statistically significant.")
else:
    print("  The difference in O3 Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_dfAZ['SO2 Mean'], after_split_dfAZ['SO2 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for SO2 Mean (before vs after {split_date.date()}) in Arizona:")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in SO2 Mean between the two periods is statistically significant.")
else:
    print("  The difference in SO2 Mean between the two periods is not statistically significant.")

ttest_result = stats.ttest_ind(before_split_dfAZ['NO2 Mean'], after_split_dfAZ['NO2 Mean'], nan_policy='omit')

print(f"Independent Samples T-test results for NO2 Mean (before vs after {split_date.date()}) in Arizona:")
print(f"  T-statistic: {ttest_result.statistic:.4f}")
print(f"  P-value: {ttest_result.pvalue:.4f}")

# Interpret the results
alpha = 0.05
if ttest_result.pvalue < alpha:
    print("  The difference in NO2 Mean between the two periods is statistically significant.")
else:
    print("  The difference in NO2 Mean between the two periods is not statistically significant.")